from os import getenv


# Common configuration for applications
class BaseConfig:
    NOTIFY_OTEL_EXPORT_TYPE = getenv("OTEL_EXPORT_TYPE", "none")
    NOTIFY_OTEL_COLLECTOR_ENDPOINT = getenv("OTEL_COLLECTOR_ENDPOINT", "localhost:4317")
    NOTIFY_OTEL_COLLECTOR_INSECURE = getenv("OTEL_COLLECTOR_INSECURE", "true").lower() in ("true", "1", "yes")

    NOTIFY_OTEL_INSTRUMENTATION_HTTP_CAPTURE_HEADERS_SERVER_REQUEST = getenv(
        "OTEL_INSTRUMENTATION_HTTP_CAPTURE_HEADERS_SERVER_REQUEST", ".*"
    )
    NOTIFY_OTEL_INSTRUMENTATION_HTTP_CAPTURE_HEADERS_SERVER_RESPONSE = getenv(
        "OTEL_INSTRUMENTATION_HTTP_CAPTURE_HEADERS_SERVER_RESPONSE", ".*"
    )

    NOTIFY_OTEL_INSTRUMENTATION_HTTP_CAPTURE_HEADERS_SANITIZE_FIELDS = getenv(
        "OTEL_INSTRUMENTATION_HTTP_CAPTURE_HEADERS_SANITIZE_FIELDS", "authorization,.*cookie.*,.*session.*"
    )

    NOTIFY_OTEL_PYTHON_FLASK_EXCLUDED_URLS = getenv("OTEL_PYTHON_FLASK_EXCLUDED_URLS", "_status(\\?.*)?$,/metrics")

    NOTIFY_OTEL_METRIC_EXPORT_INTERVAL = getenv("OTEL_METRIC_EXPORT_INTERVAL", "15s")
    NOTIFY_OTEL_METRIC_EXPORT_TIMEOUT = getenv("OTEL_METRIC_EXPORT_TIMEOUT", "30s")
