# This file is autogenerated.
#
# To update or resolve merge conflicts run one of:
# - `make version-major` for breaking changes
# - `make version-minor` for new features
# - `make version-patch` for bug fixes

__version__ = "101.0.0"  # 684a3d0ed9c4e25be421e19d7cffdfb2
